sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t dffull0245/docker-react -f dev.Dockerfile .

script:
  - docker run -e CI=true dffull0245/docker-react npm run test
