sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t dffull0245/docker-react -f dev.Dockerfile .

script:
  - docker run -e CI=true dffull0245/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-273141615927
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
