version: '3'
services:
  frontend:
    ports:
      - "8080:8080"
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
